### ISSUE TITLE
Prepare for android release

### ISSUE THREAD

**Issue by BulcsuFarmasi** [BulcsuFarmasi/konfiso#46]
- [x] Dark mode #24  
- [x] Android 12 Animation #43 
- [x] Grid sizing #44 
- [x] Link book cover on category #47 
- [x] Change the trigger for input animation #50 
- [x] Put buttons in order #54
